name: Sync Fork

on:
  schedule:
    # Runs automatically every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: 
    # Allows you to run this workflow manually from the Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to update the branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync with upstream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Syncs the 'main' branch of this repository with the parent repository
          gh repo sync BaleshSrle/IPTV --branch master
